import {calculate,gradeGrid,initialGrid,validateGrid,pasteGrid,address,position,ROWS,COLS,type Grid} from './workbook';
import {useState,useMemo,useRef} from 'react';
import type {Language} from '../types';
import {evaluate,copyFormula,valuesEqual,FormulaError,type Value} from './engine';
import {exercises} from './exercises';
export const practiceUI={
 en:{sheet:'Practice sheet',formula:'Your formula',check:'Check formula',correct:'Correct. Your formula also passed the copy or changed-data checks.',wrong:'The result does not match the task yet. Check the ranges and conditions.',robust:'The first result is right, but copying or changed data exposes a problem. Check references and conditions.',result:'Your result',empty:'Enter a formula starting with =.',unsupported:'This mini-sheet does not support that function yet. Compare your solution with the answer below.',syntax:'The formula could not be calculated. Check parentheses, arguments and cell references.',support:'Supported: SUM, AVERAGE, IF, ROUND, SUMIFS, COUNTIF, XLOOKUP, FILTER, UNIQUE, SORT, SUMPRODUCT, IFERROR (cell errors). English and the Polish equivalents shown in answers; use a decimal point and comma or semicolon separators.',saved:'Saved',save:'Save for later',remove:'Remove bookmark',list:'Bookmarks',none:'No bookmarks yet. Use “Save for later” on any puzzle.',close:'Back',storage:'Changes are kept for this visit, but your browser could not save them.',copy:'Copied down automatically',checkData:'Checks include changed input data.',output:'Result cell'},
 pl:{sheet:'Arkusz do ćwiczeń',formula:'Twoja formuła',check:'Sprawdź formułę',correct:'Dobrze! Formuła przeszła też sprawdzanie kopiowania lub zmienionych danych.',wrong:'Wynik jeszcze nie odpowiada zadaniu. Sprawdź zakresy i warunki.',robust:'Pierwszy wynik jest poprawny, ale kopiowanie lub zmiana danych ujawnia problem. Sprawdź adresy i warunki.',result:'Twój wynik',empty:'Wpisz formułę zaczynającą się od =.',unsupported:'Miniarkusz jeszcze nie obsługuje tej funkcji. Porównaj swoje rozwiązanie z odpowiedzią poniżej.',syntax:'Nie udało się obliczyć formuły. Sprawdź nawiasy, argumenty i adresy komórek.',support:'Obsługiwane: SUM, AVERAGE, IF, ROUND, SUMIFS, COUNTIF, XLOOKUP, FILTER, UNIQUE, SORT, SUMPRODUCT, IFERROR (błędy w komórkach) oraz polskie odpowiedniki podane w odpowiedziach. Używaj kropki dziesiętnej i przecinków lub średników między argumentami.',saved:'Zapisane',save:'Zapisz na później',remove:'Usuń zakładkę',list:'Zakładki',none:'Nie masz jeszcze zakładek. Wybierz „Zapisz na później” przy dowolnym zadaniu.',close:'Wróć',storage:'Zmiany są zachowane na czas wizyty, ale przeglądarka nie mogła ich zapisać.',copy:'Automatycznie skopiowano w dół',checkData:'Sprawdzamy również zmianę danych wejściowych.',output:'Komórka wyniku'},
 ru:{sheet:'Учебный лист',formula:'Твоя формула',check:'Проверить формулу',correct:'Верно! Проверка копирования или изменённых данных тоже пройдена.',wrong:'Результат пока не соответствует задаче. Проверь диапазоны и условия.',robust:'Первый результат верен, но копирование или изменение данных выявляет ошибку. Проверь ссылки и условия.',result:'Твой результат',empty:'Введи формулу, начинающуюся с =.',unsupported:'Эта функция пока не поддерживается. Сравни решение с ответом ниже.',syntax:'Не удалось вычислить формулу. Проверь скобки, аргументы и ссылки.',support:'Поддерживаются SUM, AVERAGE, IF, ROUND, SUMIFS, COUNTIF, XLOOKUP, FILTER, UNIQUE, SORT, SUMPRODUCT, IFERROR (ошибки ячеек). Используй английские имена, десятичную точку и запятые или точки с запятой между аргументами.',saved:'Сохранено',save:'Сохранить на потом',remove:'Убрать закладку',list:'Закладки',none:'Закладок пока нет. Сохрани любую задачу на потом.',close:'Назад',storage:'Изменения доступны до конца визита, но браузер не смог их сохранить.',copy:'Автоматически скопировано вниз',checkData:'Проверка включает изменение исходных данных.',output:'Ячейка результата'},
 zh:{sheet:'练习工作表',formula:'你的公式',check:'检查公式',correct:'正确！复制或数据变化检查也已通过。',wrong:'结果尚不符合题意，请检查区域和条件。',robust:'第一个结果正确，但复制或改变数据后出现问题，请检查引用和条件。',result:'你的结果',empty:'输入以 = 开头的公式。',unsupported:'此迷你工作表暂不支持该函数，请与下方答案对照。',syntax:'无法计算公式，请检查括号、参数和单元格引用。',support:'支持 SUM、AVERAGE、IF、ROUND、SUMIFS、COUNTIF、XLOOKUP、FILTER、UNIQUE、SORT、SUMPRODUCT、IFERROR（单元格错误）。请使用英文函数名、英文小数点以及逗号或分号参数分隔符。',saved:'已保存',save:'保存以便稍后练习',remove:'移除书签',list:'书签',none:'暂无书签，可以在任意题目中选择保存。',close:'返回',storage:'本次访问期间保留更改，但浏览器无法持久保存。',copy:'已自动向下复制',checkData:'检查还包括改变输入数据。',output:'结果单元格'}
};
const display=(v:Value):string=>Array.isArray(v)?v.map(display).join(' · '):v===null?'':typeof v==='boolean'?String(v).toUpperCase():typeof v==='number'?String(Math.round(v*1e8)/1e8):v;
export function checkExercise(id:string,formula:string){const ex=exercises[id];const value=evaluate(formula,ex.cells);if(!valuesEqual(value,ex.expected))return {value,status:'wrong' as const};
 const copies=Array.from({length:ex.copyRows??0},(_,i)=>evaluate(copyFormula(formula,i+1),ex.cells));
 const robust=copies.every((v,i)=>valuesEqual(v,ex.copiedExpected![i]))&&(ex.alternatives??[]).every(a=>valuesEqual(evaluate(formula,{...ex.cells,...a.cells}),a.expected));
 return {value,copies,status:robust?'correct' as const:'robust' as const};}
const editorUI={
 en:{cell:'Cell',check:'Check exercise',fill:'Fill down',undo:'Undo',reset:'Restore exercise data',hint:'Click cells to edit. Enter / Tab and arrows move between cells. Shift + arrows or Shift + click selects a range. Ctrl/Cmd+C and V copy and paste ranges.',grading:'Checking uses the original exercise inputs and additional scenarios. Your edits stay in the sheet.',incomplete:'Complete the remaining result cells, or select a range and use Fill down.',paste:'The pasted range exceeds this 20 by 8 sheet.',spill:'Edit the first cell of this spilled formula.',range:'Selection'},
 pl:{cell:'Komórka',check:'Sprawdź zadanie',fill:'Wypełnij w dół',undo:'Cofnij zmianę',reset:'Przywróć dane zadania',hint:'Kliknij komórkę, aby pisać. Enter / Tab i strzałki przenoszą do kolejnej komórki. Shift + strzałki lub Shift + kliknięcie zaznaczają zakres. Ctrl/Cmd+C i V kopiują i wklejają zakresy.',grading:'Sprawdzanie używa pierwotnych danych zadania i dodatkowych wariantów. Twoje zmiany zostają w arkuszu.',incomplete:'Uzupełnij pozostałe komórki wyniku lub zaznacz zakres i użyj Wypełnij w dół.',paste:'Zakres przekracza rozmiar arkusza 20 na 8.',spill:'Edytuj pierwszą komórkę tej rozlanej formuły.',range:'Zaznaczenie'},
 ru:{cell:'Ячейка',check:'Проверить задание',fill:'Заполнить вниз',undo:'Отменить',reset:'Восстановить данные',hint:'Нажми ячейку для ввода. Enter, Tab и стрелки перемещают курсор. Shift со стрелками или щелчком выделяет диапазон. Ctrl/Cmd+C и V копируют и вставляют диапазоны.',grading:'Проверка использует исходные данные и дополнительные варианты. Твои изменения остаются на листе.',incomplete:'Заполни остальные ячейки результата или выдели диапазон и заполни вниз.',paste:'Диапазон выходит за пределы листа 20 на 8.',spill:'Измени первую ячейку формулы массива.',range:'Выделение'},
 zh:{cell:'单元格',check:'检查练习',fill:'向下填充',undo:'撤销',reset:'恢复题目数据',hint:'点击单元格输入。Enter、Tab和方向键移动。Shift加方向键或点击选择区域。Ctrl/Cmd+C和V复制粘贴区域。',grading:'检查使用原始数据和其他数据情形，保留你的修改。',incomplete:'请填写其余结果单元格，或选择区域后向下填充。',paste:'范围超出20行8列工作表。',spill:'请编辑溢出公式的起始单元格。',range:'选区'}
};
export function MiniSheet({id,language}:{id:string;language:Language}){
 const ex=exercises[id],t=practiceUI[language],u=editorUI[language],key='thinking-space.grid.v1.'+id;
 const [grid,setGrid]=useState<Grid>(()=>{try{const saved=localStorage.getItem(key);if(saved)return validateGrid(JSON.parse(saved));const base=initialGrid(id),old=localStorage.getItem('thinking-space.formula.'+id);if(old)base[ex.target]=old;return base;}catch{return initialGrid(id);}});
 const [active,setActive]=useState(ex.target),[anchor,setAnchor]=useState(ex.target),[feedback,setFeedback]=useState(''),[storage,setStorage]=useState(false);
 const [history,setHistory]=useState<Grid[]>([]);const refs=useRef<Record<string,HTMLInputElement|null>>({});
 const calculated=useMemo(()=>calculate(grid),[grid]);const a=position(active),b=position(anchor);const top=Math.min(a.r,b.r),bottom=Math.max(a.r,b.r),left=Math.min(a.c,b.c),right=Math.max(a.c,b.c);
 const selected=(r:number,c:number)=>r>=top&&r<=bottom&&c>=left&&c<=right;
 function update(next:Grid,remember=true){if(remember)setHistory(h=>[...h.slice(-29),grid]);setGrid(next);setFeedback('');try{localStorage.setItem(key,JSON.stringify(next));}catch{setStorage(true);}}
 function move(r:number,c:number,extend=false){const cell=address(Math.max(0,Math.min(ROWS-1,r)),Math.max(0,Math.min(COLS-1,c)));setActive(cell);if(!extend)setAnchor(cell);queueMicrotask(()=>refs.current[cell]?.focus());}
 function fill(){const next={...grid};const end=top===bottom?Math.min(ROWS-1,top+(ex.copyRows??1)):bottom;for(let c=left;c<=right;c++){const source=grid[address(top,c)]??'';for(let r=top+1;r<=end;r++)next[address(r,c)]=source.startsWith('=')?copyFormula(source,r-top):source;}update(next);}
 function check(){try{const status=gradeGrid(id,grid);setFeedback(status==='incomplete'?u.incomplete:t[status]);}catch{setFeedback(t.syntax);}}
 return <section className="mini-sheet editable-sheet" aria-label={t.sheet}>
 <div className="sheet-bar"><strong>{t.sheet}</strong><span>{u.range}: {address(top,left)}{active!==anchor?':'+address(bottom,right):''}</span></div>
 <div className="sheet-edit-bar"><label htmlFor={'formula-'+id}>{active}</label><span aria-hidden="true">ƒx</span><input id={'formula-'+id} aria-label={`${t.formula} · ${active}`} value={grid[active]??''} readOnly={!!calculated.spill[active]} placeholder="=…" maxLength={1000} spellCheck={false} onChange={e=>update({...grid,[active]:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();move(a.r+1,a.c);}}}/></div>
 <div className="sheet-tools"><button onClick={fill}>{u.fill} ↓</button><button disabled={!history.length} onClick={()=>{const prev=history.at(-1);if(prev){setHistory(h=>h.slice(0,-1));update(prev,false);}}}>{u.undo} ↶</button><button onClick={()=>update(initialGrid(id))}>{u.reset}</button></div>
 <div className="sheet-scroll" role="region" aria-label={t.sheet}
 onCopy={e=>{const input=e.target as HTMLInputElement;if(active===anchor&&input.selectionEnd!==input.selectionStart)return;const raw=Array.from({length:bottom-top+1},(_,r)=>Array.from({length:right-left+1},(_,c)=>grid[address(top+r,left+c)]??'').join('\t')).join('\n');e.preventDefault();e.clipboardData.setData('text/plain',raw);e.clipboardData.setData('application/x-thinking-space-range',JSON.stringify({text:raw,origin:address(top,left)}));}}
 onPaste={e=>{e.preventDefault();try{const text=e.clipboardData.getData('text/plain');let origin:string|undefined;try{const meta=JSON.parse(e.clipboardData.getData('application/x-thinking-space-range'));if(meta.text===text&&/^[A-H](?:[1-9]|1\d|20)$/.test(meta.origin))origin=meta.origin;}catch{}update(pasteGrid(grid,text,address(top,left),origin));}catch{setFeedback(u.paste);}}}>
 <table role="grid" aria-label={t.sheet}><thead><tr><th aria-label="#"/>{Array.from({length:COLS},(_,c)=><th scope="col" key={c}>{String.fromCharCode(65+c)}</th>)}</tr></thead><tbody>{Array.from({length:ROWS},(_,r)=><tr key={r}><th scope="row">{r+1}</th>{Array.from({length:COLS},(_,c)=>{const cell=address(r,c),current=cell===active,isSpill=!!calculated.spill[cell];return <td key={c} aria-selected={selected(r,c)} className={[current?'active-cell':'',selected(r,c)?'selected-cell':'',cell===ex.target?'target-cell':''].join(' ')}><input ref={el=>{refs.current[cell]=el;}} aria-label={`${u.cell} ${cell}`} tabIndex={current?0:-1} readOnly={isSpill} value={current&&!isSpill?(grid[cell]??''):display(calculated.cells[cell]??null)} spellCheck={false} autoComplete="off" maxLength={1000} onMouseDown={e=>{if(!e.shiftKey)setAnchor(cell);setActive(cell);}} onFocus={()=>setActive(cell)} onChange={e=>update({...grid,[cell]:e.target.value})} onKeyDown={e=>{const delta:Record<string,[number,number]>={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1],Enter:[e.shiftKey?-1:1,0],Tab:[0,e.shiftKey?-1:1]};if(e.key==='Tab'){const next=r*COLS+c+(e.shiftKey?-1:1);if(next<0||next>=ROWS*COLS)return;e.preventDefault();move(Math.floor(next/COLS),next%COLS);return;}if(delta[e.key]){e.preventDefault();const [dr,dc]=delta[e.key];move(r+dr,c+dc,e.shiftKey&&e.key.startsWith('Arrow'));}if(e.key==='Escape'){setAnchor(cell);e.currentTarget.blur();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();fill();}if(e.key==='Delete'&&active!==anchor){e.preventDefault();const next={...grid};for(let rr=top;rr<=bottom;rr++)for(let cc=left;cc<=right;cc++)next[address(rr,cc)]='';update(next);}}}/></td>;})}</tr>)}</tbody></table></div>
 <p className="sheet-output">{active} · {t.result}: <output>{display(calculated.cells[active]??null)}</output>{calculated.spill[active]&&<span> — {u.spill}</span>}</p>
 <div className="sheet-check"><button className="primary" onClick={check}>{u.check} ↵</button><p>{u.grading}</p></div><div aria-live="polite">{feedback&&<p className="sheet-feedback">{feedback}</p>}{storage&&<p className="notice">{t.storage}</p>}</div>
 <details><summary>{language==='pl'?'Jak działa arkusz?':language==='ru'?'Как это работает?':language==='zh'?'如何使用？':'How does this work?'}</summary><p>{u.hint}</p><p>{t.support}</p></details>
 </section>;
}
