import type {Language} from './types';
export const names: Record<Language,string> = {en:'English',pl:'Polski',ru:'Русский',zh:'中文'};
export const ui = {
 en: {tagline:'Logic puzzles for curious minds.',eyebrow:'A little room for a big thought',intro:'Step away from the obvious. Settle into a puzzle. See where your mind takes you.',generate:'Generate a logic puzzle',another:'Try another puzzle',hint:'Give me a hint',moreHint:'Give me another hint',answer:'Show me the answer',explain:'Explain the reasoning',hintLabel:'A nudge',answerLabel:'The answer',reasonLabel:'The reasoning',exhausted:'You’ve explored every corner of this room. Ready for a fresh perspective?',reshuffle:'Reshuffle and start again',footer:'No clock. No score. Just you and a good question.',note:'Take your time. The obvious can wait.',language:'Choose language',storage:'Your browser cannot save this session. You can keep playing, but progress may be lost when you leave.',recovered:'Saved progress could not be read. A fresh session is ready.',endHints:'A little space to think. The answer is ready when you are.',puzzle:'Your thinking space',skip:'Skip to puzzle',welcome:'Make yourself curious.'},
 pl: {tagline:'Zagadki logiczne dla ciekawych świata.',eyebrow:'Mały pokój na wielką myśl',intro:'Odejdź od oczywistości. Rozgość się przy zagadce. Zobacz, dokąd zaprowadzi Cię myśl.',generate:'Wylosuj zagadkę logiczną',another:'Spróbuj kolejnej zagadki',hint:'Poproszę wskazówkę',moreHint:'Poproszę kolejną wskazówkę',answer:'Pokaż odpowiedź',explain:'Wyjaśnij rozumowanie',hintLabel:'Mała podpowiedź',answerLabel:'Odpowiedź',reasonLabel:'Rozumowanie',exhausted:'Wszystkie zakamarki tego pokoju zostały odkryte. Czas spojrzeć na nie na nowo?',reshuffle:'Przetasuj i zacznij od nowa',footer:'Bez zegara. Bez punktów. Tylko Ty i dobre pytanie.',note:'Nie spiesz się. Oczywistość może poczekać.',language:'Wybierz język',storage:'Przeglądarka nie może zapisać tej sesji. Możesz grać dalej, ale po wyjściu postęp może zostać utracony.',recovered:'Nie udało się odczytać zapisanego postępu. Nowa sesja jest gotowa.',endHints:'Chwila na namysł. Odpowiedź poczeka.',puzzle:'Twoja przestrzeń do myślenia',skip:'Przejdź do zagadki',welcome:'Rozgość się z ciekawością.'},
 ru: {tagline:'Логические задачи для любознательных.',eyebrow:'Немного места для большой мысли',intro:'Отвлекитесь от очевидного. Устройтесь поудобнее с задачей. Посмотрите, куда приведёт вас мысль.',generate:'Выбрать логическую задачу',another:'Попробовать другую задачу',hint:'Дайте подсказку',moreHint:'Дайте ещё подсказку',answer:'Показать ответ',explain:'Объяснить решение',hintLabel:'Небольшая подсказка',answerLabel:'Ответ',reasonLabel:'Ход рассуждений',exhausted:'Вы исследовали все уголки этой комнаты. Готовы взглянуть на них по-новому?',reshuffle:'Перемешать и начать заново',footer:'Без таймера. Без очков. Только вы и хороший вопрос.',note:'Не торопитесь. Очевидное подождёт.',language:'Выбрать язык',storage:'Браузер не может сохранить эту сессию. Можно продолжать, но при выходе прогресс может быть потерян.',recovered:'Не удалось прочитать сохранённый прогресс. Можно начать новую сессию.',endHints:'Немного времени подумать. Ответ подождёт.',puzzle:'Ваше пространство для размышлений',skip:'Перейти к задаче',welcome:'Дайте волю любопытству.'},
 zh: {tagline:'献给好奇心的逻辑谜题。',eyebrow:'一方小天地，容得下大思考',intro:'暂别显而易见的答案，静下心来解一道题，看看思绪会带你走向何处。',generate:'随机抽取逻辑谜题',another:'再试一道谜题',hint:'给我一个提示',moreHint:'再给我一个提示',answer:'显示答案',explain:'解释推理过程',hintLabel:'一点提示',answerLabel:'答案',reasonLabel:'推理过程',exhausted:'你已探索过这里的每个角落。准备换个角度，重新出发吗？',reshuffle:'重新洗牌并开始',footer:'不计时，不计分。只有你和一道好题。',note:'慢慢来，显而易见的答案可以等等。',language:'选择语言',storage:'浏览器无法保存本次进度。你可以继续，但离开后进度可能丢失。',recovered:'无法读取已保存的进度。可以开始新的练习。',endHints:'留一点时间思考。答案会等你准备好。',puzzle:'你的思考空间',skip:'跳转到谜题',welcome:'让好奇心坐下来。'}
} satisfies Record<Language,Record<string,string>>;

export const shelfText = {
 en:{choose:'Choose your next challenge.',subtitle:'A quick twist or a proper head-scratcher? Open a book.',back:'Back to the bookshelf',gentle:'Easy',intermediate:'Medium',challenging:'Complex',gentleDesc:'Everyday things. Unexpected answers.',intermediateDesc:'Connect the clues. Find the clever move.',challengingDesc:'Big problems. Beautiful solutions.',open:'Open book',chapter:'A question to sit with'},
 pl:{choose:'Wybierz swoje wyzwanie.',subtitle:'Krótka zagadka czy porządna rozkmina? Otwórz książkę.',back:'Wróć do wyboru poziomu',gentle:'Łatwy',intermediate:'Średni',challenging:'Skomplikowany',gentleDesc:'Zwykłe rzeczy. Nieoczywiste odpowiedzi.',intermediateDesc:'Połącz wskazówki. Znajdź sprytny ruch.',challengingDesc:'Duże wyzwania. Zaskakujące rozwiązania.',open:'Otwórz książkę',chapter:'Pytanie na dobrą chwilę'},
 ru:{choose:'Выбери свой вызов.',subtitle:'Короткая загадка или серьёзная задачка? Открой книгу.',back:'К выбору сложности',gentle:'Лёгкий',intermediate:'Средний',challenging:'Сложный',gentleDesc:'Обычные вещи. Неожиданные ответы.',intermediateDesc:'Соедини подсказки. Найди хитрый ход.',challengingDesc:'Большие задачи. Красивые решения.',open:'Открыть книгу',chapter:'Вопрос для размышлений'},
 zh:{choose:'选择你的下一项挑战。',subtitle:'轻松一猜，还是认真推敲？打开一本书。',back:'返回选择难度',gentle:'简单',intermediate:'中等',challenging:'复杂',gentleDesc:'日常事物，意外答案。',intermediateDesc:'串联线索，找到巧妙的一步。',challengingDesc:'深入挑战，精彩解法。',open:'打开书本',chapter:'值得想一想的问题'}
};

export const modeText = {
 en:{logic:'Puzzles',select:'Choose collection',excelTitle:'Think outside the cell.',excelIntro:'Excel exercises. Three levels. Open a workbook.',formulaNote:'Formulas use English function names and commas. Your Excel language and regional settings may require translated names and semicolons.',open:'Open workbook',next:'Try another exercise'},
 pl:{logic:'Zagadki',select:'Wybierz dział',excelTitle:'Wyjdź poza komórkę.',excelIntro:'Zadania z Excela. Trzy poziomy. Otwórz zeszyt.',formulaNote:'Formuły zapisano angielskimi nazwami funkcji i z przecinkami. Polski Excel zwykle wymaga polskich nazw i średników; odpowiedniki podajemy w rozwiązaniach.',open:'Otwórz zeszyt',next:'Kolejne zadanie'},
 ru:{logic:'Загадки',select:'Выбери раздел',excelTitle:'Думай за пределами ячейки.',excelIntro:'Задания по Excel. Три уровня. Открой тетрадь.',formulaNote:'Формулы используют английские имена функций и запятые. Язык и региональные настройки Excel могут требовать переведённых имён и точек с запятой.',open:'Открыть тетрадь',next:'Следующее задание'},
 zh:{logic:'谜题',select:'选择分类',excelTitle:'跳出单元格思考。',excelIntro:'Excel 练习，三个难度。打开练习本。',formulaNote:'公式使用英文函数名和逗号。Excel 的语言及区域设置可能要求本地化函数名和分号。',open:'打开练习本',next:'下一道练习'}
};
